#!/bin/bash
#
# Copyright 2016 The Open Source Research Group,
#                University of Erlangen-Nürnberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -ue

# This script is always executed in the **root** of your repository

# Build the apk file
./gradlew clean build

# Copy apk file to docker/assets directory
echo
echo "Copying final artifact to docker assets directory"
rm -rf ./docker/assets/*.apk
mkdir -p ./docker/assets
cp -v ./build/outputs/apk/*-debug.apk ./docker/assets/demo-app-debug.apk

# Androd + Docker currently not supported by Travis CI
if [ "${TRAVIS_CI_BUILD:-false}" != true ]; then
  # Build docker image
  # --pull: Make sure that the newest version of the base image is always pulled
  docker build --pull -t osrgroup/android-app-example-project:1.0 docker/
fi
